export const languages = {
  english: {
    api: {
      action: {
        register: "Register",
        update: "Update",
        search: "Search",
        delete: "Delete",
      },
      entities: {
        user: "User",
        company: "Company",
        schedule: "Schedule",
        time: "Time",
        commitment: "Commitment",
      },
      message: {
        serverFailure: "Server Failure",
        errorDuplication: "Duplication Error",
        errorDataTooLong: "Data Too Long Error",
        missingParameters: "Missing Parameters",
        unauthorized: "Unauthorized",
        errorCredentials: "Credentials Error",
        authenticationRequired: "Authentication Required",
        successfulRegistration: "Registration Successful",
        errorRegistration: "Registration Error",
        errorSearch: "Search Error",
        errorUpdate: "Update Error",
        successfulUpdate: "Update Successful",
        successfulDelete: "Delete Successful",
        errorDelete: "Delete Error",
      },
    },
    alert: {
      create: "Create",
      find: "Find",
      list: "List",
      update: "Update",
      delete: "Delete",

      confirm: "Confirm",
      cancel: "Cancel",
    },
    pageSchedule: {
      sunday: "Sunday",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
    },
  },
  portuguese: {
    api: {
      action: {
        register: "Registrar",
        update: "Atualizar",
        search: "Buscar",
        delete: "Apagar",
      },
      entities: {
        entity: "Usuário ou Empresa",
        user: "Usuário",
        company: "Empresa",
        schedule: "Agendamento",
        time: "Horário",
        commitment: "Compromisso",
      },
      message: {
        serverFailure: "Falha no Servidor",
        errorDuplication: "Erro de Duplicação",
        errorDataTooLong: "Dados Muito Longos",
        missingParameters: "Parâmetros Ausentes",
        unauthorized: "Não Autorizado",
        errorCredentials: "Erro de Credenciais",
        authenticationRequired: "Autenticação Necessária",
        successfulRegistration: "Registro Bem-Sucedido",
        errorRegistration: "Erro no Registro",
        errorSearch: "Erro na Busca",
        errorUpdate: "Erro na Atualização",
        successfulUpdate: "Atualização Bem-Sucedida",
        successfulDelete: "Exclusão Bem-Sucedida",
        errorDelete: "Erro na Exclusão",
      },
    },
    alert: {
      create: "Cadastrar",
      find: "Buscar",
      list: "Listar",
      update: "Alterar",
      delete: "Apagar",

      confirm: "Confirmar",
      cancel: "Cancelar",
    },
    pageSchedule: {
      sunday: "Domingo",
      monday: "Segunda-feira",
      tuesday: "Terça-feira",
      wednesday: "Quarta-feira",
      thursday: "Quinta-feira",
      friday: "Sexta-feira",
      saturday: "Sábado",
    },
  },
};
